image: docker/compose:alpine-1.26.0

variables:
  # DOCKERFILE
  DOCKERFILE: 'Dockerfile'

  REPO_NAME: 'jodykpw/universal-nginx-php73'
  TAG: "1.0.0"
  DEV_TAG: $TAG-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

# MASTER
.master_ci_job: &master_ci_job
  only:
    - master
  environment:
    name: master 
  tags:
    - docker-01.example.shared.docker

.master_ci_manual_job: &master_ci_manual_job
  when: manual
  <<: *master_ci_job

# DEVELOPMENT
.dev_ci_job: &dev_ci_job
  only:
    - dev
  environment:
    name: dev 
  tags:
    - docker-01.example.shared.docker

.dev_ci_manual_job: &dev_ci_manual_job
  when: manual
  <<: *dev_ci_job

stages:
  - "Build"
  - "Docker Composer Up"
  - "Test Docker Container"
  - "Docker Composer Down"
  - "Release"
  - "On Failure Cleanup"

before_script:
  - docker version
  - docker-compose version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.example.com

"Build":
  stage: "Build"
  script:
    - echo Build started on `date` for $DEV_TAG
    - docker build -t $REPO_NAME:$DEV_TAG -f $DOCKERFILE .
  <<: *dev_ci_job 

"Docker Composer Up":
  stage: "Docker Composer Up"
  script:
    - REPO_NAME=$REPO_NAME TAG=$DEV_TAG docker-compose -f docker-compose-build-test.yml up -d   
  <<: *dev_ci_job 

"Test Docker Container":
  stage: "Test Docker Container"
  script:
    - sleep 20
    - docker exec -i  universal-nginx-php-test nginx -c /etc/nginx/nginx.conf -t
    - docker exec -i  universal-nginx-php-test php -m
    - docker exec -i  universal-nginx-php-test composer -v
    - docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost/healthz
    - docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9001/status/format/json
    - docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9000/status
    - docker exec -i  universal-nginx-php-test ps aux    
  <<: *dev_ci_job 

"Docker Composer Down":
  stage: "Docker Composer Down"
  script:
    - REPO_NAME=$REPO_NAME TAG=$DEV_TAG docker-compose -f docker-compose-build-test.yml down
    - docker rmi $REPO_NAME:$DEV_TAG
  <<: *dev_ci_job 

"Release to Docker Hub":
  stage: "Release"
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD   
    - docker build -t $REPO_NAME:$TAG -f $DOCKERFILE .
    - docker push $REPO_NAME:$TAG
  <<: *master_ci_job

"Docker Composer Down":
  stage: "On Failure Cleanup"
  script:
    - REPO_NAME=$REPO_NAME TAG=$DEV_TAG docker-compose -f docker-compose-build-test.yml down
  when: on_failure

"Docker Remove DEV Image":
  stage: "On Failure Cleanup"
  script:
    - docker rmi $REPO_NAME:$DEV_TAG
  when: on_failure