version: '3'

services:
  web:
    image: jodykpw/universal-nginx-php73:1.0.0
    container_name: universal-nginx-php
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080" # Nginx Exporter
      - "9913:9913" # PHP-FPM Exporter
    environment:
      MONITORING: 'false'
      DOCKER_CRON: 'false'
    volumes:
      - nginx_config:/etc/nginx
      - php_config:/etc/php/7.3
      - www_data:/var/www/html

volumes:
  nginx_config: 
  php_config: 
  www_data: 