version: '3'

services:
  web:
    image: ${REPO_NAME}:${TAG}
    container_name: universal-nginx-php-test
    restart: always
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "8081:8080" # Nginx Exporter
    #   - "9913:9913" # PHP-FPM Exporter
    environment:
      MONITORING: 'true'
      DOCKER_CRON: 'false'