version: '3'

services:
  web:
    image: jodykpw/universal-nginx-php73:1.0.0
    container_name: universal-nginx-php73
    restart: always
    ports:
      - "8081:8080" # Nginx Exporter
      - "9913:9913" # PHP-FPM Exporter
    networks:
      - traefik
    environment:
      MONITORING: 'false'
      DOCKER_CRON: 'false'
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/php/7.3:/etc/php/7.3
      - ./data/www:/var/www
      # - ./data/docker-cron/crontab:/etc/cron.d/crontab
    labels:
      # Dynamic configuration with Docker Labels
      # Ref: https://docs.traefik.io/reference/dynamic-configuration/docker/
      - traefik.enable=true
      - traefik.http.middlewares.php-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.php-web.middlewares=php-redirect-web-secure
      - traefik.http.routers.php-web.rule=Host(`${HOST}`)
      - traefik.http.routers.php-web.entrypoints=web
      - traefik.http.routers.php-web-secure.rule=Host(`${HOST}`)
      - traefik.http.routers.php-web-secure.tls=true
      - traefik.http.routers.php-web-secure.entrypoints=web-secure
      # if you have multiple ports exposed on the service, specify port in the web-secure service
      - traefik.http.services.php-web-secure.loadbalancer.server.port=80

networks:
  traefik:
    external: true