def app

pipeline {
    agent any

    environment {
        EMAIL_TO = 'team@example.com'
        EMAIL_REPLY_TO = 'jenkins@example.com'
        EMAIL_MIME_TYPE = 'text/html'
        EMAIL_ATTACH_LOG = 'true'

        HARBOR_DOMAIN = 'harbor.example.com'
        HARBOR_CREDENTIALS = 'harbor'
        DOCKERHUB_CREDENTIALS = 'dockerhub'
        REPO_NAME = 'jodykpw/universal-nginx-php73'
        TAG = '1.0.0'
        COMMIT_SHORT_SHA = """${sh(
                returnStdout: true,
                script: 'git rev-parse --short=8 HEAD'
            ).trim()}"""
        DEV_TAG = "${env.TAG}-${env.BRANCH_NAME}-${env.COMMIT_SHORT_SHA}"
    }

    parameters {
        booleanParam(name: 'Vulnerability', defaultValue: false, description: '')
    }

    stages {
        stage("SCM") {
            steps {
                checkout scm
            }
            post {
                success {
                    echo "========SCM: executed successfully========"
                }
                failure {
                    echo "========SCM: execution failed========"
                }
            }
        }

        stage("Build") {
            steps {
                script {
                    if ( env.BRANCH_NAME == "master" ) {
                        app = docker.build("${env.REPO_NAME}:${TAG}")
                                        
                    } else {
                        app = docker.build("${env.REPO_NAME}:${env.DEV_TAG}")
                    }
                }
            }
            post {
                success {
                    echo "========Build: executed successfully========"
                }
                failure {
                    echo "========Build: execution failed========"
                }
            }
        }

        stage("Test") {
            steps {
                sh script: "REPO_NAME=${env.REPO_NAME} TAG=${env.DEV_TAG} docker-compose -f docker-compose-build-test.yml up -d", label: "Docker Compose Up"

                script {
                    try {
                        sh 'sleep 20'
                        sh 'docker exec -i  universal-nginx-php-test nginx -c /etc/nginx/nginx.conf -t'
                        sh 'docker exec -i  universal-nginx-php-test php -m'
                        sh 'docker exec -i  universal-nginx-php-test composer -v'
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost/healthz' 
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9001/status/format/json' 
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9000/status' 
                        sh 'docker exec -i  universal-nginx-php-test ps aux'  

                        sh script: "REPO_NAME=${env.REPO_NAME} TAG=${env.DEV_TAG} docker-compose -f docker-compose-build-test.yml down", label: "Docker Compose Down"
          
                        if ( env.BRANCH_NAME != "master" ) {
                            sh script: "docker rmi ${env.REPO_NAME}:${env.DEV_TAG}", label: "Untagged/Delete Development Docker Image."
                        }
                                              
                    } catch (Exception e) {
                        sh "REPO_NAME=${env.REPO_NAME} TAG=${env.DEV_TAG} docker-compose -f docker-compose-build-test.yml down", label: "Docker Compose Down"

                        if ( env.BRANCH_NAME != "master" ) {
                            sh script: "docker rmi ${env.REPO_NAME}:${env.DEV_TAG}", label: "Untagged/Delete Development Docker Image."
                        }

                        sh 'exit 1'
                    }
                }

            }
            post{
                success {
                    echo "========Test: executed successfully========"
                }
                failure {
                    echo "========Test: execution failed========"
                }
            }
        }

        stage("Vulnerability") {
            when {
                expression { params.Vulnerability == true }
            }
            steps {
                script {
                    docker.withRegistry("https://${env.HARBOR_DOMAIN}", "${env.HARBOR_CREDENTIALS}") {
                        app = docker.build("${env.HARBOR_DOMAIN}/${env.REPO_NAME}:${env.DEV_TAG}")
                        app.push()
                    }
                }
            }
            post {
                success {
                    echo "========Release: executed successfully========"
                }
                failure {
                    echo "========Release: execution failed========"
                }
            }
        }

        stage("Release") {
            when {
                expression { env.BRANCH_NAME == "master" }
            }
            steps {
                sh script: "REPO_NAME=${env.REPO_NAME} TAG=${env.TAG} docker-compose -f docker-compose-build-test.yml up -d", label: "Docker Compose Up"

                script {
                    try {
                        sh 'sleep 20'
                        sh 'docker exec -i  universal-nginx-php-test nginx -c /etc/nginx/nginx.conf -t'
                        sh 'docker exec -i  universal-nginx-php-test php -m'
                        sh 'docker exec -i  universal-nginx-php-test composer -v'
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost/healthz' 
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9001/status/format/json' 
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9000/status' 
                        sh 'docker exec -i  universal-nginx-php-test ps aux'  

                        sh script: "REPO_NAME=${env.REPO_NAME} TAG=${env.TAG} docker-compose -f docker-compose-build-test.yml down", label: "Docker Compose Down"
          
                        docker.withRegistry("", "${env.DOCKERHUB_CREDENTIALS}") {
                            app.push()
                        }
                                              
                    } catch (Exception e) {
                        sh "REPO_NAME=${env.REPO_NAME} TAG=${env.TAG} docker-compose -f docker-compose-build-test.yml down", label: "Docker Compose Down"

                        if ( env.BRANCH_NAME != "master" ) {
                            sh script: "docker rmi ${env.REPO_NAME}:${env.TAG}", label: "Untagged/Delete Development Docker Image."
                        }

                        sh 'exit 1'
                    }
                }

            }
            post {
                success {
                    echo "========Release: executed successfully========"
                }
                failure {
                    echo "========Release: execution failed========"
                }
            }
        }

    }

    post {
        success {
            echo "========Pipeline executed successfully ========"

            emailext(body: "The pipeline ${env.BUILD_URL} completed successfully.", mimeType: "${EMAIL_MIME_TYPE}",
                replyTo: "${EMAIL_REPLY_TO}", subject: "Success Pipeline: ${currentBuild.fullDisplayName}",
                to: "${EMAIL_TO}", attachLog: "${EMAIL_ATTACH_LOG}")
        }
        failure {
            echo "========Pipeline execution failed========"

            emailext(body: "Something is wrong with ${env.BUILD_URL}", mimeType: "${EMAIL_MIME_TYPE}",
                replyTo: "${EMAIL_REPLY_TO}", subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                to: "${EMAIL_TO}", attachLog: "${EMAIL_ATTACH_LOG}")
        }
    }
}