def app
def tag

pipeline {
    agent any

    environment {
        EMAIL_TO = 'team@example.com'
        EMAIL_REPLY_TO = 'jenkins@example.com'
        EMAIL_MIME_TYPE = 'text/html'
        EMAIL_ATTACH_LOG = 'true'

        HARBOR_DOMAIN = 'harbor.example.com'
        HARBOR_CREDENTIALS = 'harbor'
        DOCKERHUB_CREDENTIALS = 'dockerhub'
        REPO_NAME = 'jodykpw/universal-nginx-php73'
        VERSION = '1.0.0'
        COMMIT_SHORT_SHA = """${sh(
                returnStdout: true,
                script: 'git rev-parse --short=8 HEAD'
            ).trim()}"""
    }

    parameters {
        booleanParam(name: 'Sync', defaultValue: false, description: '')
        booleanParam(name: 'Vulnerability', defaultValue: false, description: '')
    }

    stages {
        stage("SCM") {
            steps {
                checkout scm

                script {
                    if ( env.BRANCH_NAME == "master" || env.BRANCH_NAME == "production" ) {
                        tag = "${env.VERSION}"           
                    } else {
                        tag = "${env.VERSION}-${env.BRANCH_NAME}-${env.COMMIT_SHORT_SHA}"
                    }
                }

            }
            post {
                success {
                    echo "========SCM: executed successfully========"
                }
                failure {
                    echo "========SCM: execution failed========"
                }
            }
        }

        stage("Build") {
            when {
                expression { params.Sync == false }
            }
            steps {
                script {
                    app = docker.build("${env.REPO_NAME}:${tag}")  
                }
            }
            post {
                success {
                    echo "========Build: executed successfully========"
                }
                failure {
                    echo "========Build: execution failed========"
                }
            }
        }

        stage("Test") {
            when {
                expression { params.Sync == false }
            }
            steps {
                script {
                    sh script: "REPO_NAME=${env.REPO_NAME} TAG=${tag} docker-compose -f docker-compose-build-test.yml up -d", label: "Docker Compose Up"
                }

                script {
                    try {
                        sh 'sleep 20'
                        sh 'docker exec -i  universal-nginx-php-test nginx -c /etc/nginx/nginx.conf -t'
                        sh 'docker exec -i  universal-nginx-php-test php -m'
                        sh 'docker exec -i  universal-nginx-php-test composer -v'
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost/healthz' 
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9001/status/format/json' 
                        sh 'docker exec -i  universal-nginx-php-test curl --silent --show-error --fail http://localhost:9000/status' 
                        sh 'docker exec -i  universal-nginx-php-test ps aux'  

                        sh script: "REPO_NAME=${env.REPO_NAME} TAG=${tag} docker-compose -f docker-compose-build-test.yml down", label: "Docker Compose Down"                                              
                    } catch (Exception e) { 
                        sh script: "REPO_NAME=${env.REPO_NAME} TAG=${tag} docker-compose -f docker-compose-build-test.yml down", label: "Docker Compose Down"
                        sh 'exit 1'
                    }
                }

            }
            post{
                success {
                    echo "========Test: executed successfully========"
                }
                failure {
                    echo "========Test: execution failed========"
                }
            }
        }

        stage("Vulnerability") {
            when {
                allOf {
                    expression{params.Vulnerability == true}
                    expression{params.Sync == false}
                }
            }

            steps {
                script {
                    docker.withRegistry("https://${env.HARBOR_DOMAIN}", "${env.HARBOR_CREDENTIALS}") {
                        app = docker.build("${env.HARBOR_DOMAIN}/${env.REPO_NAME}:${tag}")
                        app.push()
                    }
                }
            }
            post {
                success {
                    echo "========Release: executed successfully========"
                }
                failure {
                    echo "========Release: execution failed========"
                }
            }
        }

        stage("Release") {
            when {
                allOf {
                    expression{env.BRANCH_NAME ==~ /(master|production)/}
                    expression{ params.Sync == false } 
                }
            }
            steps {
                script {
                    docker.withRegistry("", "${env.DOCKERHUB_CREDENTIALS}") {
                        app.push()
                    }
                }
            }
            post {
                success {
                    echo "========Release: executed successfully========"
                }
                failure {
                    echo "========Release: execution failed========"
                }
            }
        }

        stage("Cleanup") {
            when {
                allOf {
                    expression{env.BRANCH_NAME !=~ /(master|production)/}
                    expression{ params.Sync == false } 
                }
            }
            steps {
                script {
                    sh script: "docker rmi ${env.REPO_NAME}:${tag}", label: "Untagged/Delete Development Docker Image."
                }
            }
            post {
                success {
                    echo "========Release: executed successfully========"
                }
                failure {
                    echo "========Release: execution failed========"
                }
            }
        }
    }

    post {
        success {
            echo "========Pipeline executed successfully ========"

            emailext(body: "The pipeline ${env.BUILD_URL} completed successfully.", mimeType: "${EMAIL_MIME_TYPE}",
                replyTo: "${EMAIL_REPLY_TO}", subject: "Success Pipeline: ${currentBuild.fullDisplayName}",
                to: "${EMAIL_TO}", attachLog: "${EMAIL_ATTACH_LOG}")
        }
        failure {
            echo "========Pipeline execution failed========"

            emailext(body: "Something is wrong with ${env.BUILD_URL}", mimeType: "${EMAIL_MIME_TYPE}",
                replyTo: "${EMAIL_REPLY_TO}", subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                to: "${EMAIL_TO}", attachLog: "${EMAIL_ATTACH_LOG}")
        }
    }
}